---
title: "case_when"
format: html
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(haven) 
library(tidyverse) 
library(clean) 
library(labelled) 
library(Hmisc) 

df <- read_sav('/Users/joecrowley/R/Data/BSA Teaching Data/spss/spss25/bsa2019_poverty_open.sav', user_na = T)

```

Recoding variables based on other variables, mostly using `case_when`.

<br>

## Simple case_when

```{r}

df %>% count(RAgeCat)

df <- df %>% mutate(age2 = case_when( 
  RAgeCat %in% c(1,2,3) ~ 1, 
  RAgeCat %in% c(4,5,6,7) ~ 2, 
  TRUE ~ NA)
  , 
  age2 = factor(age2, labels = c("18 - 44", "45 +")) 
  )

df %>% count(RAgeCat, age2)

```

<br> 

## Recoding drawing on several variables

Identify left-wing Tories.

```{r}

# convenience function to run count() for all of a vector of variables
count_df <- function(df, vars) {
  map(vars, 
      ~df %>%
        mutate_at(.x, ~as_factor(.x, levels = "both")) %>%
        count(across(all_of(.x))) %>% 
        mutate(var = .x) %>% 
        rename(cat = .x) %>% 
        relocate(var)
      ) %>%
    bind_rows
}

df %>% count_df(c("PartyId2", "leftrigh")) %>% print(n=100)

df <- df %>% mutate(left_wing_tory = case_when(
  PartyId2 == 1 & zap_missing(leftrigh) < 2.5 ~ 1, 
  PartyId2 == 1 & zap_missing(leftrigh) >= 2.5 ~ 2, 
  PartyId2 %in% 2:8 ~ 3
  ), 
  left_wing_tory = 
    factor(left_wing_tory, 
           levels = 1:3, 
           labels = c( "Left wing Tory", "Tory", "Other parties")
           ) 
  )

df %>% count(left_wing_tory)

df %>% count(left_wing_tory, as_factor(PartyId2))
df %>% count(left_wing_tory, as_factor(leftrigh, levels = "both"))

```

<br> 

### Recoding drawing on several variables using tidy-select

Identify people with extreme responses on BSA attitude scales.

```{r}
#| warning: false

df %>% 
  count_df(vars = c("libauth", "leftrigh", "welfare2")) %>% 
  print(n=100) 

cleaner::freq(df$libauth, nmax=100, sort.count = F)

vars <- c("libauth", "leftrigh", "welfare2") 

df <- df %>% mutate(extremes = case_when(
  # Values above 5 or below zero are NA 
  if_any(all_of(vars), ~. < 0 | . > 5) ~ NA,
  # Cases with any value above 4 or below two are 1
  if_any(all_of(vars), ~ . >= 4 & . <= 5) ~ 1, 
  if_any(all_of(vars), ~ . <= 2 & . >= 0) ~ 1, 
  # Remaining values zero 
  TRUE ~ 0)
  )

# extremes defined as reporting values greater than 4 or less than 2 on any score

df %>% count(extremes)

df %>% select(extremes, libauth, leftrigh, welfare2) %>% sample_n(20)

df %>% group_by(extremes) %>% 
  summarise(across(all_of(vars), 
                   list(min = min, max = max))
            ) %>% 
  pivot_longer(cols = -extremes) %>% 
  separate(name, c("var","stat"), sep = "_") %>% 
  pivot_wider(names_from = stat, values_from = value)

```

<br>

### case_when across multiple variables

```{r}

df %>% glimpse

vars <- c("welfare2", "leftrigh", "libauth")

df <- df %>% mutate(across(vars, 
  ~factor(case_when(.x >= 0 & .x < 2 ~ 1, 
             .x >= 2 & .x <= 4 ~ 2, 
             .x > 4 & .x <=5 ~ 3), 
          labels = c("Low","Medium","High")), 
  .names = "{.col}_2"
  ))

df %>% count(welfare2, welfare2_2)

```

<br> 

#### Quick check

```{r}
check_recode <- function(df, vars, suffix) {
  for (var in vars) {
    new_var <- paste0(var, suffix)
    cat("\n===", var, "===========================\n")
    result <- count(df, .data[[var]], .data[[new_var]])
    print(result, n = nrow(result))
    cat("\n")
  }
}

check_recode(df, vars, suffix = "_2")

```

