---
title: "Renaming"
format: html
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(here)
here::i_am("Renaming.qmd")
library(haven) 
library(tidyverse) 
library(clean) 
library(labelled) 
library(Hmisc) 

df <- read_sav(here::here("data", "synthetic_bsa2019_sav.sav"), user_na = TRUE)

```

<br>

## One variable at a time

```{r}

df %>% names

df %>% rename(sex = RSex, `Weight variable` = WtFactor, serial_number = Sserial) %>% 
  names

```

<br>

## General edits

```{r}

df %>% rename_all(tolower) %>% names

```

## tidy-select

```{r}

# Using tidy-select to identify variables, and apply a function
df %>% select(libauth, leftrigh, welfare2) %>% glimpse

df %>% select(libauth, leftrigh, welfare2) %>% 
  rename_with(~paste0(.x, "_f"), .cols = everything()) %>% 
  names()

```

## Use an external vector

Rename with an external vector of names

```{r}

# Uses a named vector...
lookup <- c(`Left-right scale` = "leftrigh", 
            `Libertarian-authoritarian scale` = "libauth", 
            `Welfarism scale` = "welfare2", 
            dole = "Dole"
            )

rename(df, all_of(lookup)) %>% names

```

